version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my5QLw0rdpr3ss
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./webdata:/var/www/html

  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my5QLw0rdpr3ss
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./dbdata:/var/lib/mysql
